// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm7ATqmk9PXvGU0V1pJPUedgoSynZF9Os',
    appId: '1:202313896579:web:911bc256adf030a72fc1b6',
    messagingSenderId: '202313896579',
    projectId: 'acuaflex-41372',
    authDomain: 'acuaflex-41372.firebaseapp.com',
    storageBucket: 'acuaflex-41372.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaeEIaAsuWjq7dBo_zxVvKmb_tI8MvO_8',
    appId: '1:202313896579:android:1d6b238844cce65d2fc1b6',
    messagingSenderId: '202313896579',
    projectId: 'acuaflex-41372',
    storageBucket: 'acuaflex-41372.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrtKQN9qC_p2lrjKuDFA6oU0UT4F87Gh0',
    appId: '1:202313896579:ios:0f8ea9e181d5d2732fc1b6',
    messagingSenderId: '202313896579',
    projectId: 'acuaflex-41372',
    storageBucket: 'acuaflex-41372.appspot.com',
    iosBundleId: 'com.example.acuaflexV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrtKQN9qC_p2lrjKuDFA6oU0UT4F87Gh0',
    appId: '1:202313896579:ios:0f8ea9e181d5d2732fc1b6',
    messagingSenderId: '202313896579',
    projectId: 'acuaflex-41372',
    storageBucket: 'acuaflex-41372.appspot.com',
    iosBundleId: 'com.example.acuaflexV1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCm7ATqmk9PXvGU0V1pJPUedgoSynZF9Os',
    appId: '1:202313896579:web:04974fd14d794c9d2fc1b6',
    messagingSenderId: '202313896579',
    projectId: 'acuaflex-41372',
    authDomain: 'acuaflex-41372.firebaseapp.com',
    storageBucket: 'acuaflex-41372.appspot.com',
  );
}
